language: python
python:
- '3.4'
env:
- MEERKAT_ABACUS_DB_URL='postgresql+psycopg2://postgres:postgres@localhost/meerkat_db'
addons:
  postgresql: '9.4'
services:
- postgresql
install:
- pip install -r requirements.txt
- git clone https://github.com/who-emro/meerkat_abacus.git
- pip install -r meerkat_abacus/requirements.txt
- cd meerkat_abacus
- python meerkat_abacus/manage.py all
- cd ..

script: nosetests
