language: python
python:
- '3.4'
env:
- MEERKAT_ABACUS_DB_URL='postgresql+psycopg2://postgres:postgres@localhost/meerkat_db' MEERKAT_BRANCH='set-up-api' MEERKAT_API_SETTINGS='.travis_config'
addons:
  postgresql: '9.4'
services:
- postgresql
install:
- pip install -r requirements.txt
- git clone https://github.com/who-emro/meerkat_abacus.git
- pip install -r meerkat_abacus/requirements.txt
- cd meerkat_abacus
- git checkout $MEERKAT_BRANCH
- pip install .
- python meerkat_abacus/manage.py all
- cd ..

script: nosetests
